name: Twitter Bot Auto-Poster

on:
  # Pemicu berdasarkan jadwal (cron job)
  schedule:
    # Jalankan setiap 1 jam sekali
    - cron: '0 * * * *'
  
  # Pemicu manual (agar bisa dites kapan saja dari tab Actions di GitHub)
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter Bot Script
        env:
          # Masukkan nama secret yang sudah Anda buat di Settings
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
